### ISSUE TITLE
FS- ancien client - ENG

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#10]
Les textes ne sont pas bons : 

Hello XXXX XXXXX

If, at Freakshow, we are the writers and directors of a film dedicated to a brand that has come to shake up the world of optics, then opticians are the main partners and actors, those without whom nothing would be possible!

So thank you for your trust and your loyalty! Your commitment to our brand inspires us and inspires us. Together, we will always go further to reveal the most creative and original part of each eyeglass wearer!

To keep you informed of our news (news, highlights, events ...) we will send you regular newsletters and we post every day on our social networks. Follow us ! (emoticons FB + INSTA + TWITTER + YOUTUBE)

Your satisfaction is important to us, and we will meet again in a few months.

In the meantime, the reseller area of the Angel Eyes website has been designed for YOU. Orders, After Sales Service, Marketing Tools, Sales aids: we simplify your life by making all these services available 24 hours a day, 7 days a week.
Each transaction on your reseller space allows you to accumulate points as part of our loyalty program. These points will make you benefit from discounts on Freakshow derivative items!

We hope that your order will give you complete satisfaction and thank you for your trust.

See you soon ! Reflect Yourself!

CTA : my optician account / Opticians zone

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis Mettre les émoticones dans l'ordre facebook instagram twitter youtube
