### ISSUE TITLE
FS- nouveau client - ENG

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#11]
Les textes ne sont pas bons:

Welcome to you in the great Freakshow family, and thank you for this great choice. Together we will reveal the most creative and original side of each eyeglass wearer!

The world of optics is a sector in full evolution, and Freakshow makes a point of honor to inscribe durably its arty and trendy touch.

Dynamism and innovation are at the heart of our identity, as evidenced by our inexhaustible creative energy.

To keep you informed of our news (news, highlights, events ...) we will send you regular newsletters and we post every day on our social networks. Follow us ! (emoticons FB + INSTA + TWITTER + YOUTUBE)
Your satisfaction is important to us, and we will meet again in a few months.

In the meantime, the reseller area of the Angel Eyes website has been designed for YOU. Orders, After Sales Service, Marketing Tools, Sales aids: we simplify your life by making all these services available 24 hours a day, 7 days a week.
Each transaction on your reseller space allows you to accumulate points as part of our loyalty program. These points will make you benefit from discounts on Freakshow derivative items!

We hope that your order will give you complete satisfaction and thank you for your trust.

See you soon ! Reflect Yourself!

CTA : my optician account /Opticians zone

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis Mettre dans l'ordre les émoticones : facebook instagram twitter Youtube

**Comment by teraluis** [comment]
traite
