### ISSUE TITLE
VF - premier client - FR

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#2]
https://teraluis.github.io/mail_remerciment/VF-NOUVEAU-CLIENT-FR.html

- supprimer le doublon "Vous avez fait l’excellent choix de passer du côté rock de l’optique. Bravo et merci ! Vinyl Factory, c’est l’histoire d’une petite marque devenue grande grâce à des partenaires visionnaires et dynamiques ! Tout semble indiquer que vous allez être comme un poisson dans l’eau dans ce grand bain à remous !"
- rajouter : Le monde de l’optique, plus qu’un autre, est un secteur en pleine évolution, et Vinyl Factory est bien déterminée à y implanter durablement son univers rock et décalé.
Le dynamisme et l'innovation sont au cœur de notre identité, comme le prouve notre inépuisable énergie créatrice.
- mettre l'émoticone instagram après facebook
- supprimer : "Le dynamisme, l'innovation sont au coeur de notre identité, notre énergie créatrice en est la preuve"
- rajouter avant "A très vite": "Nous espérons que votre commande vous donnera entière satisfaction et vous remercions pour votre confiance."

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis supprimer la phrase qui est en dessous de rendez-vous dans quelques mois :  "Le dynamisme, l'innovation sont au coeur de notre identité, notre énergie créatrice en est la preuve"

**Comment by teraluis** [comment]
effectue
