### ISSUE TITLE
VF- ancien client-ESP 

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#4]
- aller à la ligne à partir de  ¡Así que, gracias!
- aller à la ligne à partir de   El mundo
- émoticone instagram après celle de facebook
- rajouter en dessous à la ligne de la semana : Cada transacción en su espacio personal de nuestra web, además, también le permitirá acumular puntos como parte de nuestro programa de fidelización. ¡Estos puntos le harán beneficiarte de descuentos en artículos de nuestro catálogo de complementos de Vinyl Factory!

**Comment by teraluis** [comment]
traite

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis le footer n'est pas en ESP : contáctenos / Síguenos
