### ISSUE TITLE
VF - nouveau client ESP

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#5]
- aller à la ligne à partir de  Vinyl Factory es la historia 
- aller à la ligne à partir de El mundo de la óptica, 
- aller à la ligne à partir de El dinamismo...
- mettre l'émoticone de instagram après facebook
- aller à la ligne à partir de Cada transacción en su espacio personal de nuestra web
- le footer n'est pas en ESP : contáctenos / Síguenos

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis mettre à la ligne de  Vinyl Factory es la historia...
mettre à la ligne de El mundo de la óptica,...
mettre à la ligne El dinamismo...
mettre à la ligne Cada transacción en su espacio personal de nuestra web...
le footer n'est pas en ESP : contáctenos / Síguenos

**Comment by teraluis** [comment]
traite en local
