### ISSUE TITLE
FS- ancien client - ESP

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#6]
- les liens des émoticônes sont ceux de VF, il faut mettre FS
- rajouter après complementos de FS: Esperamos que su pedido le brinde una completa satisfacción y le agradecemos su confianza.
- lien CTA : zona de opticas 
- mettre le bon lien de zona de opticas

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis mettre dans l'ordre facebook instagram twitter youtube 
le lien de l'émoticone de twitter n'est pas le bon

sauter une ligne et mettre à la ligne la phrase Esperamos...

lien CTA : zona de opticas

**Comment by teraluis** [comment]
raite en local
