### ISSUE TITLE
FS- nouveau client - ESP 

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#7]
- sauter une ligne et aller à la ligne à partir de : El mundo 
- sauter une ligne et aller à la ligne à partir de : El dinamismo 
- mettre l'émoticone de instagram après facebook
- changer : IR A MI AREA OPTICA par ve a mi espacio
-changer le CTA par : zona de opticas
- footer : contáctenos

**Comment by teraluis** [comment]
traite en local

**Comment by CloGo** [comment]
@teraluis mettre El Mundo à la ligne
mettre El dinamismo à la ligne

**Comment by teraluis** [comment]
traite en local
