### ISSUE TITLE
VF -  nouveau client - ENG

### ISSUE THREAD

**Issue by CloGo** [teraluis/mail_remerciment#9]

**Comment by CloGo** [comment]
- il manque le texte après  hot tub! : aller à la ligne : The world of optics, more than any other, is a sector in full evolution, and Vinyl Factory is determined to implement durably its rock universe and offbeat.
Dynamism and innovation are at the heart of our identity, as evidenced by our inexhaustible creative energy.
- émoticone INSTA après FB
- supprimer la phrase en FR : Le dynamisme, l'innovation sont au coeur de notre identité, notre énergie créatrice en est la preuve
- aller à la ligne à partir de : Each transaction 
- rajouter à la ligne après objects : We hope that your order will give you complete satisfaction and thank you for your trust.

**Comment by teraluis** [comment]
traite en local
